### ISSUE TITLE
Broken readme.md link

### ISSUE THREAD

**Issue by pchandle** [SoftwareVerde/bitcoin-verde#16]
Under the getting started section of readme.md, the documentation link is 404 not found.
`For more detailed instructions, please refer to https://bitcoinverde.org/documentation/`

**Comment by pchandle** [comment]
Is this the proper target? `https://explorer.bitcoinverde.org/documentation/`

**Comment by joshmg** [comment]
Hi @pchandle !  Thank you for reporting the broken link.  We've resolved this broken link in version v2.1.0.
