### ISSUE TITLE
UTXO Fast-Sync: Consider using VARINT for all of the integers in the serialized UTXO

### ISSUE THREAD

**Issue by cculianu** [SoftwareVerde/bitcoin-verde#21]
For example, UTXO output value is now 8-bytes fixes size.  A quick scan of the UTXO set shows that fully 80% of the UTXOs right now, or ~41 million UTXOs, could be encoded in a 5-byte compactsize.  That's a 150MB savings right there just for this 1 field.  And there are a few other fields in the same data structure that likely can benefit (such as "height and is_coinbase"), as well as likely output number.

Together this may be around 1GB of savings or in that ballpark just for the current UTXO set.

It's something to think about doing.

**Comment by cculianu** [comment]
Not yet no.. but I can update it. Let me know if/when you plan to do it so I do it too. (Although our nodes aren't talking to each other now anyway so synchronization on this change in time is not super-critical .. so long as we are all on same page eventually).

**Comment by cculianu** [comment]
Ok, updated in BCHN. I'm still testing it now. See #22 for a PR that highlights what I have changed.

**Comment by joshmg** [comment]
Implemented in Verde: https://github.com/SoftwareVerde/bitcoin-verde/commit/79f1e2d7783d3781f7ed25c37c007a023907e6c8
