### ISSUE TITLE
secp256k1 provided by Bitcoin-ABC

### ISSUE THREAD

**Issue by hegjon** [SoftwareVerde/bitcoin-verde#6]
Hi, Amaury Séchet at Bitcoin-ABC have started a new git repo where he keeps a clone of the secp256k1 part from the main software.

I noticed that you ship with an old version from Bitcoin-core that does not support Schnorr.

I can help you if you need pre-built binaries from Fedora releases. Since we will start shipping the Bitcoin-ABC version for Fedora soon. https://koji.fedoraproject.org/koji/taskinfo?taskID=40070498

**Comment by joshmg** [comment]
Hey Jonny!  Thanks for letting us know about the secp256k1 repo.  We're definitely interested in upgrading and have added this issue to our tracking board.  Once progress gets made, we'll update here.

We should have the resources to compile the prebuilt binaries ourselves, but I also see value in having binaries that are signed with the same key used in the Fedora repos; perhaps that could be something we explore.  Once we pull that card we'll reach out and see what options make sense.

Thanks again!

**Comment by thesquaregroot** [comment]
No longer planned, as Bitcoin-ABC is now defunct.
